#!/bin/sh

USR_NAME="WestleyR"
PKG_NAME="clc"
NAME="clc"

PKG_VERSION=`curl -s "https://api.github.com/repos/${USR_NAME}/${PKG_NAME}/commits/master" | get-json-value`

TARBALL="https://github.com/${USR_NAME}/${PKG_NAME}/archive/${PKG_VERSION}.tar.gz"

UNTAR_DIR="${PKG_NAME}-*"

# Load the prefix
. load_gpack ${PKG_NAME}

INSTALL_CMD="make && mkdir -p ${gpack_prefix}/bin && cp ./clc ${gpack_prefix}/bin/clc"

