#!/bin/sh

USR_NAME="WestleyR"
PKG_NAME="ssum"
NAME="lib-ssum"
PKG_VERSION="3.0.0"

TARBALL="https://github.com/${USR_NAME}/${PKG_NAME}/archive/v${PKG_VERSION}.tar.gz"
SHA256SUM="799e0fab0f7465f1c380ee5b2b5222d4392ac69e3961efe01b12acee9d000234"

UNTAR_DIR="${PKG_NAME}-${PKG_VERSION}"

# Load the prefix
. load_gpack ${PKG_NAME}

BUILD_CMD="./configure --prefix ${gpack_prefix} && make libssum.1.so && make install-lib"
BUILD_LIB_FILES="lib/libssum.1.so"
BUILD_INCLUDE_FILES="include/ssum.1.h"

# Linux Ubuntu
#X86_64_LINUX_URL="https://github.com/${USR_NAME}/${PKG_NAME}/releases/download/v${PKG_VERSION}/lib-ssum-v${PKG_VERSION}-x86_64_linux.tar.gz"
#X86_64_LINUX_SHA256SUM="1a7dc99d7608bc306f48c304a8f1da59f7c4b659e345b61201997e1be84d78e0"

