#!/bin/sh

USR_NAME="WestleyR"
PKG_NAME="list-files"
NAME="list-files"
PKG_VERSION="1.6.0"

SHA256SUM="37061e1866610117d610a1bfe3449095bb40c09b20217dd277f4e378bce497eb"

TARBALL="https://github.com/${USR_NAME}/${PKG_NAME}/archive/v${PKG_VERSION}.tar.gz"
UNTAR_DIR="${PKG_NAME}-${PKG_VERSION}"

# Linux Ubuntu
X86_64_LINUX_URL="https://github.com/${USR_NAME}/${PKG_NAME}/releases/download/v${PKG_VERSION}/lf-v${PKG_VERSION}-x86_64_linux.tar.gz"
X86_64_LINUX_SHA256SUM="2bb94715b1e673ee15f57c3be8dc8b873c4f6bd27516d2ec7409f9307beb6f40"

# NO PRECOMPILED BINARIES FOR THESE ARCH YET
## Macos
#MACOS_URL="https://github.com/${USR_NAME}/${PKG_NAME}/releases/download/v${PKG_VERSION}/lf-v${PKG_VERSION}-macos.tar.gz"
#MACOS_SHA256SUM="b9a4127ccdca64e9d306e38077fef286e561d11d4565392ca73d643236c7d693"
#
## Raspberry pi zero (and others)
#ARMV6L_URL="https://github.com/${USR_NAME}/${PKG_NAME}/releases/download/v${PKG_VERSION}/lf-v${PKG_VERSION}-armv6l.tar.gz"
#ARMV6L_SHA256SUM="45e57bc4274239d032e4afcfe63f36edd5b52ca215e2f8e10c5eef8f4ee4e928"

# Load the prefix
. load_gpack ${PKG_NAME}

INSTALL_CMD="make install PREFIX=${gpack_prefix}"

