#!/bin/sh

USR_NAME="WestleyR"
PKG_NAME="list-files"
NAME="list-files"
PKG_VERSION="1.6.2"

SHA256SUM="56e6ab605cea0205a3bb061ccb15c71b0764b31983c2509b746637ea1bd7dee0"

TARBALL="https://github.com/${USR_NAME}/${PKG_NAME}/archive/v${PKG_VERSION}.tar.gz"
UNTAR_DIR="${PKG_NAME}-${PKG_VERSION}"

# Linux Ubuntu
#X86_64_LINUX_URL="https://github.com/${USR_NAME}/${PKG_NAME}/releases/download/v${PKG_VERSION}/lf-v${PKG_VERSION}-x86_64_linux.tar.gz"
#X86_64_LINUX_SHA256SUM=""

# Macos
MACOS_URL="https://github.com/${USR_NAME}/${PKG_NAME}/releases/download/v${PKG_VERSION}/lf-v${PKG_VERSION}-macos.tar.gz"
MACOS_SHA256SUM="4dd8dd847ca70a60bbdbf88fdaf217846c499c6b15da6800f25914f7127dd4d1"

# NO PRECOMPILED BINARIES FOR THESE ARCH YET
## Raspberry pi zero (and others)
#ARMV6L_URL="https://github.com/${USR_NAME}/${PKG_NAME}/releases/download/v${PKG_VERSION}/lf-v${PKG_VERSION}-armv6l.tar.gz"
#ARMV6L_SHA256SUM="45e57bc4274239d032e4afcfe63f36edd5b52ca215e2f8e10c5eef8f4ee4e928"

# Load the prefix
. load_gpack ${PKG_NAME}

INSTALL_CMD="make install PREFIX=${gpack_prefix}"

