#!/bin/sh
#
# This simple script takes a data file (more on that later) and plots a graph
# to a png file, using gnuplot.
#
# This data file should contain two coloms, like:
#
#    $ cat data.txt
#    5.00  0.00
#    5.01  0.10
#    5.00  0.20
#    ...
#
#
# The file should be called "data.txt", and be in the current directory as you
# are running this command in.
#
# The output file will be a png, and will be called "output.png". THIS WILL
# OVERIDE THE FILE IS IT ALREADY EXISTS!
#
# Usage:
#    $ ls
#    data.txt
#
#    $ plot-voltage-time-graph
#
#    $ ls
#    data.txt  output.png
#

USR_NAME="WestleyR"
PKG_NAME="plot-volage-time-into-png"
NAME="plot-voltage-graph"

GISTID="124ff82093df6d59d308f272a0fbf4ed"

PKG_VERSION=`curl -s "https://api.github.com/gists/${GISTID}" | get-json-value version`

RAW_FILE="https://gist.githubusercontent.com/WestleyR/${GISTID}/raw/${PKG_VERSION}/plot-volage-time-into-png"

# Load the prefix
. load_gpack ${PKG_NAME}

INSTALL_CMD="pwd ; ls ; chmod +x ${NAME} && mkdir -p ${gpack_prefix}/bin && cp -f ${NAME} ${gpack_prefix}/bin"

