#!/bin/sh

USR_NAME="WestleyR"
PKG_NAME="srm"
NAME="srm"
PKG_VERSION="2.0.0.a1"

#SHA256SUM=""

TARBALL="https://github.com/${USR_NAME}/${PKG_NAME}/archive/v${PKG_VERSION}.tar.gz"
UNTAR_DIR="${PKG_NAME}-${PKG_VERSION}"

#
# Precompiled binaries
#

# Linux Ubuntu
X86_64_LINUX_URL="https://github.com/${USR_NAME}/${PKG_NAME}/releases/download/v${PKG_VERSION}/srm-v${PKG_VERSION}-x86_64_linux.tar.gz"
X86_64_LINUX_SHA256SUM="ac720a51ae8517d45253f227adfffc7bc9e4b9448f842bba08c6adde42617d93"

# Macos
MACOS_URL="https://github.com/${USR_NAME}/${PKG_NAME}/releases/download/v${PKG_VERSION}/srm-v${PKG_VERSION}-macos.tar.gz"
MACOS_SHA256SUM="0e6d44e9923cd774d5fbeafecf3d28349e6804f677d4044391881bad691f92ed"

# Raspberry pi zero (and others)
ARMV6L_URL="https://github.com/${USR_NAME}/${PKG_NAME}/releases/download/v${PKG_VERSION}/srm-v${PKG_VERSION}-armv6l.tar.gz"
ARMV6L_SHA256SUM="c52200929ab4b80a482252a9936e58f94db9233248ebc138723561d689428625"


# Load the prefix
#. load_gpack ${PKG_NAME}

INSTALL_NOTES="Recommended that you a you rm command: (just add this to your .bashrc)
alias rm="srm"
"

NOTES="This is a beta software, please report bugs/feature requests to https://github.com/WestleyR/srm
"

#INSTALL_CMD="make install PREFIX=${gpack_prefix}"

# The command(s) only to build, installing the
# files is handled by BIN_FILES, LIB_FILES,
# INCLUDE_FILES, and ETC_FILES.
BUILD_CMD="make GOFLAGS+=-o=srm"

# The final file command path after building.
BUILD_BIN_FILES="srm"

# The path to the command from the pre-built package.
BIN_FILES="bin/srm"

