#!/bin/sh

USR_NAME="WestleyR"
PKG_NAME="srm"
NAME="srm"
PKG_VERSION="1.1.1"

SHA256SUM="2d3662a910e0a5342e5ba9ba97e0a743003166c8acbe4dc8d5e61acd90c29808"

TARBALL="https://github.com/${USR_NAME}/${PKG_NAME}/archive/v${PKG_VERSION}.tar.gz"
UNTAR_DIR="${PKG_NAME}-${PKG_VERSION}"

# Linux Ubuntu
X86_64_LINUX_URL="https://github.com/${USR_NAME}/${PKG_NAME}/releases/download/v${PKG_VERSION}/srm-v${PKG_VERSION}-x86_64_linux.tar.gz"
X86_64_LINUX_SHA256SUM="57fac6d92a5a7715abb551d428fee316123e9894389d6e7cda6a0bb414959c70"

# Load the prefix
. load_gpack ${PKG_NAME}

INSTALL_NOTES="Recommended that you a you rm command: (just add this to your .bashrc)
alias rm="srm"
"

INSTALL_CMD="make install PREFIX=${gpack_prefix}"

