#!/bin/sh

USR_NAME="WestleyR"
PKG_NAME="ssum"
NAME="ssum"

PKG_VERSION=`curl -s "https://api.github.com/repos/${USR_NAME}/${PKG_NAME}/commits/master" | get-json-value`

TARBALL="https://github.com/${USR_NAME}/${PKG_NAME}/archive/${PKG_VERSION}.tar.gz"

UNTAR_DIR="${PKG_NAME}-*"

BUILD_CMD="./configure --prefix /tmp --without-library && make"
BUILD_BIN_FILES="ssum"

