#!/bin/sh

#
# Please see: https://github.com/stolk/imcat for more details on this package.
#

USR_NAME="stolk"
PKG_NAME="imcat"
NAME="imcat"

PKG_VERSION=`curl -s "https://api.github.com/repos/${USR_NAME}/${PKG_NAME}/commits/master" | get-json-value`

TARBALL="https://github.com/${USR_NAME}/${PKG_NAME}/archive/${PKG_VERSION}.tar.gz"

UNTAR_DIR="${PKG_NAME}-*"

# Load the prefix
. load_gpack ${PKG_NAME}

# Need to build manually since there is errors on macOS
BUILD_CMD="gcc -Wall -o imcat imcat.c"

BUILD_BIN_FILES="imcat"

