#!/bin/sh

#
# Please see: https://github.com/stolk/imcat for more details on this package.
#

USR_NAME="stolk"
PKG_NAME="imcat"
NAME="imcat"

PKG_VERSION=`curl -s "https://api.github.com/repos/${USR_NAME}/${PKG_NAME}/commits/master" | get-json-value`

TARBALL="https://github.com/${USR_NAME}/${PKG_NAME}/archive/${PKG_VERSION}.tar.gz"

UNTAR_DIR="${PKG_NAME}-*"

# Load the prefix
. load_gpack ${PKG_NAME}

# The current Makefile does not support install, yet...
# So we need to install it manually.
INSTALL_CMD="make && mkdir -p ${gpack_prefix}/bin && cp -f imcat ${gpack_prefix}/bin"

