#!/bin/sh

#
# Please see: https://github.com/clibs/clib for more details on this package.
#

USR_NAME="clibs"
PKG_NAME="clib"
NAME="clib"

PKG_VERSION=`curl -s "https://api.github.com/repos/${USR_NAME}/${PKG_NAME}/commits/master" | get-json-value`

TARBALL="https://github.com/${USR_NAME}/${PKG_NAME}/archive/${PKG_VERSION}.tar.gz"

UNTAR_DIR="${PKG_NAME}-*"

# Load the prefix
. load_gpack ${PKG_NAME}

INSTALL_CMD="make install PREFIX=${gpack_prefix}"

